"""Create gyms table

Revision ID: 21d01af0c8e3
Revises:
Create Date: 2022-04-09 19:44:50.934106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21d01af0c8e3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gyms",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gyms")
    # ### end Alembic commands ###
