"""Create gym activity association table

Revision ID: 38ccb9a1b385
Revises: af78be27a2e7
Create Date: 2022-04-12 05:18:38.391014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "38ccb9a1b385"
down_revision = "af78be27a2e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gym_activities",
        sa.Column("gym_name", sa.String(), nullable=True),
        sa.Column("activity_name", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_name"],
            ["activities.name"],
        ),
        sa.ForeignKeyConstraint(
            ["gym_name"],
            ["gyms.name"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gym_activities")
    # ### end Alembic commands ###
