"""Create activities table

Revision ID: af78be27a2e7
Revises: 21d01af0c8e3
Create Date: 2022-04-12 04:25:50.227628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af78be27a2e7"
down_revision = "21d01af0c8e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activities")
    # ### end Alembic commands ###
